### ISSUE TITLE
own version tag for changes

### ISSUE THREAD

**Issue by jumoog** [wader/static-ffmpeg#189]
First of all, thank you for your work!
Maybe it's a good idea to create your own versions as a tag? 
For example, if you update svtav1 from 0.9.1 to 1.0.0 you could create version 5.0.1.**1**
Then dependabot will also find a new version.  Otherwise people will stay on version 5.0.1 for a long time and not get the new changes.

**Comment by wader** [comment]
Thanks, glad to hear it's useful!

Yes that is good idea. I've done some -N versions at times when it felt important. I think some kind of automation for this would be good for this. Wonder if a github action could auto tag with -N (or .N) where N is commits since latest non -N tag etc? or would that be annoying?

btw do you know if dependabot works well with 1.2.3-N or 1.2.3.N versions schemes? i think that for semver 1.2.3-N is seen as pre-releases for 1.2.4 so might not work that well.

**Comment by jumoog** [comment]
> btw do you know if dependabot works well with 1.2.3-N or 1.2.3.N versions schemes? i think that for semver 1.2.3-N is seen as pre-releases for 1.2.4 so might not work that well.

I'll try that tomorrow and let you know.

**Comment by jumoog** [comment]
In the default config `5.0.1.1` will be ignored 

```
updater | INFO <job_361835597> Latest version is 5.0.1.1
updater | INFO <job_361835597> No update needed for jumoog/grive 5.0.1
updater | INFO <job_361835597> Finished job processing
```
`5.0.1.1`, on the other hand, is not found at all

```
updater | INFO <job_361836119> Latest version is 5.0.1
updater | INFO <job_361836119> No update needed for jumoog/grive 5.0.1
updater | INFO <job_361836119> Finished job processing
```

**Comment by wader** [comment]
Ok thanks for testing. That is a bit of a problem :( when work on bump i ran into these issues quite a lot :) what seems to usually work with a 1.2.3-N is reverse lexical sort. Did a quick look if dependbot could be configured to use it but didn't find anything.

Any ideas? doing something involving different major, minor or patch number compared to ffmpeg might be too confusing? ex could do something like 5.0.1 -> 5.0.1000, 5.0.1.1 -> 5.0.1001 but not sure i like it.
