### ISSUE TITLE
using existing packages?

### ISSUE THREAD

**Issue by mathieu-aubin** [wader/static-ffmpeg#419]
https://pkgs.alpinelinux.org/package/edge/main/x86_64/libvorbis-static
https://pkgs.alpinelinux.org/package/edge/main/x86_64/libtheora-static
https://pkgs.alpinelinux.org/package/edge/main/x86_64/rtmpdump-static
and more... libcaca etc..

maybe consider?

**Comment by mathieu-aubin** [comment]
https://pkgs.alpinelinux.org/contents?file=*.a&path=&name=*static*&branch=edge&arch=x86_64

**Comment by mathieu-aubin** [comment]
oh, also... maybe ffmpeg could build a bit faster with `--disable-doc`

**Comment by wader** [comment]
> https://pkgs.alpinelinux.org/package/edge/main/x86_64/libvorbis-static https://pkgs.alpinelinux.org/package/edge/main/x86_64/libtheora-static https://pkgs.alpinelinux.org/package/edge/main/x86_64/rtmpdump-static and more... libcaca etc..
> 
> maybe consider?

Yeap could be interesting. Main reasons why i build from source is if alpine for some reason lags behind with updating version or to get a "hardened" build for security reasons.

Currently there is some issue with the rtmpdump patches that might take it interesting to use package instead. But don't remember the reasons for the patches, to support newer openssl?

> oh, also... maybe ffmpeg could build a bit faster with `--disable-doc`
> 
> feel free to close, hope you are doing well brother!

Mm could be considered. Why i added them initially was because the docs were used be another ffmpeg project that i haven't worked on for a long time.
